[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
    'npm run build --workspace=packages/shared',
    'npm run build --workspace=packages/web'
]

[start]
cmd = 'npm start --workspace=packages/web'