[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm config set cache /tmp/.npm-cache --global',
    'npm ci --prefer-offline --no-audit --no-fund'
]

[phases.build]
cmds = [
    'npm run build --workspace=packages/shared',
    'npm run build --workspace=packages/web'
]

[start]
cmd = 'chmod +x start.sh && ./start.sh'