[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
    'npm run build --workspace=packages/shared',
    'npm run build --workspace=packages/web'
]

[start]
cmd = 'npm start --workspace=packages/web'